# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b73ae198ba3e66f2eb46bc90e7105a359eb0646f95b4a8f679153e478d75fd2f5ab5471800e12ffcf04a60fda6bb7599cac8825c82b08636a3e96490783c92f

test:
  secret_key_base: dc905e8ddaee170828cf480912fc1dd861ac2d88f3ed4ba0fc306ee2f4e6384daa5f1df509409073b22c3cd05573c4b5a20c9045f59b29e7bd4c66adbf6311d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
